name: rgt_assessment
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Service locator
  get_it: ^7.6.6
  # Svg image rendering
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  syncfusion_flutter_charts: ^24.1.45+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  collection: ^1.18.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
